name: food_log
description: "Aplikasi Food Log untuk Pasien Diabetes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # OTP 
  http: ^1.1.0 
  cupertino_icons: ^1.0.8

  # Notifikasi lokal (pengingat obat)
  flutter_local_notifications: ^18.0.1

  # Database SQLite
  sqflite: ^2.3.0
  path: ^1.8.3

  # Penyimpanan lokal (login/session)
  shared_preferences: ^2.3.3

  # Grafik gula darah
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true